version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: airflow
      MYSQL_USER: airflow
      MYSQL_PASSWORD: airflow_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  webserver:
    image: meu-airflow
    restart: 'no'
    command: webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__WEBSERVER__SECRET_KEY=admin
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=mysql+mysqlconnector://airflow:airflow_pass@mysql:3306/airflow
      - KAGGLE_USERNAME=tarcisiopiucco
      - KAGGLE_KEY=42a7926ee6f123d7e8692561aef1788a
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    depends_on:
      - mysql

  scheduler:
    image: meu-airflow
    restart: 'no'
    command: scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__WEBSERVER__SECRET_KEY=admin
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=mysql+mysqlconnector://airflow:airflow_pass@mysql:3306/airflow
      - KAGGLE_USERNAME=tarcisiopiucco
      - KAGGLE_KEY=42a7926ee6f123d7e8692561aef1788a
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    depends_on:
      - mysql

